<?php

function quiz_quiz_finished($quiz, $score, $rid) {
  global $user;

  if (variable_get('quiz_results_to_quiz_author', 0)) {
    $author_mail = db_result(db_query('SELECT mail FROM {users} WHERE uid = %d', $quiz->uid));
    drupal_mail('quiz', 'notice', $author_mail, NULL, array($quiz, $score, $rid, 'author'));
  }

  if (variable_get('quiz_email_results', 0) && variable_get('quiz_use_passfail', 1) && $user->uid != 0 && $score['is_evaluated']) {
    drupal_mail('quiz', 'notice', $user->mail, NULL, array($quiz, $score, $rid, 'taker'));
    drupal_set_message(t('Your results have been sent to your e-mail address.'));


  profile_load_profile(&$user);
  //dsm($user);
  $pca_mail = db_result(db_query("SELECT users.uid AS uid, profile_values_profile_campus_department.value AS 
		profile_values_profile_campus_department_value, profile_values_profile_campus_department.uid AS 
		profile_values_profile_campus_department_uid, users.name AS users_name 
		FROM users users  
		INNER JOIN users_roles users_roles ON users.uid = users_roles.uid 
		LEFT JOIN profile_values profile_values_profile_campus_department 
		ON users.uid = profile_values_profile_campus_department.uid 
		AND profile_values_profile_campus_department.fid = 1
		WHERE users_roles.rid = 3
		AND profile_values_profile_campus_department.value = '%s'", $user->profile_campus_department));

    // don't mail yet since we have live email addresses
    //drupal_mail('quiz', 'notice', $pca_mail, NULL, array($quiz, $score, $rid, 'pca'));
    drupal_set_message(t('Your results have been sent to your Procard Administrator\'s e-mail address.'));
  }

  // Calls userpoints functions to credit user point based on number of correct
  // answers.
  if ($quiz->has_userpoints && $user->uid != 0 && $score['is_evaluated']) {
    
    //Looking up the tid of the selected Userpoint vocabulary
    $selected_tid = db_result(
      db_query("SELECT tid FROM {term_node}
                WHERE nid = %d AND vid = %d AND tid IN (
                  SELECT tid
                  FROM {term_data}
                  WHERE vid = %d
                )", $quiz->nid, $quiz->vid, userpoints_get_vid()));
    $variables = array(
      '@title' => $quiz->title,
      '@quiz' => variable_get('quiz_name', QUIZ_NAME),
      '@time' => date('l jS \of F Y h:i:s A'),
    );
    $params = array(
      'points' => $score['numeric_score'],
      'description' => t('Attened @title @quiz on @time', $variables),
      'tid' => $selected_tid,
    );
    userpoints_userpointsapi($params);
  }
}